# SPDX-License-Identifier: MIT-0
---
# tasks file for provision-tomcat

- name: Install tomcat
  ansible.builtin.include_tasks: install-Windows-tomcat.yml
  when: ansible_facts['os_family'] == 'Windows'
